spring:
  application:
    name: paytech-test
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-stacktrace: on_param
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.paytech.demo: DEBUG

paytech:
  base-url: https://engine-sandbox.pay.tech
  api-token: ${PAYTECH_API_TOKEN:cAmmvalAikARkB81fgxgMtnMbEdNbuWa}

rate-limit:
  requests-per-minute: 10
  requests-per-hour: 100

feign:
  retry:
    max-attempts: 3
    period: 1000
    max-period: 5000
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000